export const styles = {
  tabsRow: {
    display: "flex",
    gap: ".55rem",
    marginBottom: ".9rem",
    flexWrap: "wrap",
  },
  tabButton: {
    padding: ".48rem .8rem",
    borderRadius: 10,
    border: "1px solid #d1d5db",
    background: "#fff",
    color: "#374151",
    fontWeight: 600,
    fontSize: 13,
    cursor: "pointer",
  },
  tabButtonActive: {
    borderColor: "#a5b4fc",
    background: "#eef2ff",
    color: "#3730a3",
  },
  presencePanel: {
    marginBottom: ".9rem",
    border: "1px solid #e5e7eb",
    borderRadius: 12,
    background: "#fff",
    padding: ".65rem .75rem",
  },
  presenceHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: ".6rem",
    marginBottom: ".5rem",
  },
  presenceTitle: {
    fontSize: 12,
    fontWeight: 700,
    color: "#374151",
    textTransform: "uppercase",
    letterSpacing: ".02em",
  },
  presenceCount: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: 20,
    height: 20,
    padding: "0 .35rem",
    borderRadius: 999,
    background: "#eef2ff",
    color: "#3730a3",
    fontSize: 12,
    fontWeight: 700,
  },
  presenceEmpty: {
    fontSize: 13,
    color: "#6b7280",
  },
  presenceList: {
    display: "grid",
    gap: ".45rem",
  },
  presenceItem: {
    border: "1px solid #edf2f7",
    borderRadius: 9,
    padding: ".45rem .55rem",
    background: "#fafafa",
  },
  presenceNameRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: ".6rem",
  },
  presenceName: {
    fontSize: 13,
    fontWeight: 700,
    color: "#111827",
  },
  presenceRole: {
    fontSize: 11,
    color: "#4b5563",
    textTransform: "capitalize",
  },
  presenceMeta: {
    marginTop: ".2rem",
    display: "inline-flex",
    alignItems: "center",
    gap: ".35rem",
    fontSize: 12,
    color: "#6b7280",
  },
  notificationsPanel: {
    marginBottom: ".9rem",
    border: "1px solid #e5e7eb",
    borderRadius: 12,
    background: "#fff",
    padding: ".65rem .75rem",
  },
  notificationsHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: ".5rem",
  },
  notificationsTitle: {
    fontSize: 12,
    fontWeight: 700,
    color: "#374151",
    textTransform: "uppercase",
    letterSpacing: ".02em",
  },
  notificationsCount: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: 20,
    height: 20,
    padding: "0 .35rem",
    borderRadius: 999,
    background: "#fff7ed",
    color: "#9a3412",
    fontSize: 12,
    fontWeight: 700,
  },
  notificationsEmpty: {
    fontSize: 13,
    color: "#6b7280",
  },
  notificationsList: {
    display: "grid",
    gap: ".5rem",
  },
  notificationItem: {
    border: "1px solid #fed7aa",
    borderRadius: 10,
    background: "#fff7ed",
    padding: ".55rem .65rem",
  },
  notificationMessage: {
    fontSize: 14,
    color: "#7c2d12",
    lineHeight: 1.45,
  },
  notificationMeta: {
    marginTop: ".25rem",
    display: "inline-flex",
    gap: ".35rem",
    alignItems: "center",
    fontSize: 12,
    color: "#9a3412",
  },
  notificationReadButton: {
    marginTop: ".4rem",
    borderRadius: 8,
    border: "1px solid #fdba74",
    background: "#fff",
    color: "#9a3412",
    fontWeight: 700,
    fontSize: 12,
    padding: ".3rem .56rem",
    cursor: "pointer",
  },
  timelineHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "1rem 1rem .5rem",
    gap: ".8rem",
    flexWrap: "wrap",
  },
  timelineTitle: {
    margin: 0,
    fontSize: 16,
    color: "#111827",
  },
  timelineSubtitle: {
    fontSize: 12,
    color: "#6b7280",
    fontWeight: 600,
  },
  timelineList: {
    padding: "0 1rem 1rem",
    display: "grid",
    gap: ".55rem",
  },
  timelineItem: {
    display: "grid",
    gridTemplateColumns: "12px 1fr",
    gap: ".55rem",
    alignItems: "start",
  },
  timelineDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    marginTop: ".42rem",
    background: "#93c5fd",
  },
  timelineContent: {
    border: "1px solid #e5e7eb",
    borderRadius: 10,
    padding: ".55rem .65rem",
    background: "#fff",
  },
  timelineMessage: {
    fontSize: 14,
    color: "#111827",
    lineHeight: 1.45,
  },
  timelineMeta: {
    marginTop: ".28rem",
    fontSize: 12,
    color: "#6b7280",
    display: "inline-flex",
    alignItems: "center",
    gap: ".35rem",
  },
  timelineActor: {
    fontWeight: 700,
    color: "#374151",
  },
  timelineEmpty: {
    fontSize: 13,
    color: "#6b7280",
    border: "1px dashed #d1d5db",
    borderRadius: 10,
    padding: ".7rem .75rem",
    background: "#fafafa",
  },
  card: {
    border: "1px solid #e5e7eb",
    borderRadius: 16,
    overflow: "hidden",
    background: "#fff",
    boxShadow: "0 1px 2px rgba(0,0,0,0.04)",
  },
  companyInfoCard: {
    border: "1px solid #e5e7eb",
    borderRadius: 16,
    background: "#fff",
    boxShadow: "0 1px 2px rgba(0,0,0,0.04)",
    padding: "1rem",
    marginBottom: "1rem",
  },
  companyInfoTitle: {
    margin: 0,
    fontSize: 16,
  },
  companyInfoHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: ".75rem",
    alignItems: "center",
    flexWrap: "wrap",
    marginBottom: ".75rem",
  },
  stageButtons: {
    display: "flex",
    alignItems: "center",
    gap: ".5rem",
    flexWrap: "wrap",
  },
  companyInfoGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: ".7rem",
  },
  infoItem: {
    display: "flex",
    flexDirection: "column",
    gap: ".2rem",
    padding: ".65rem .7rem",
    border: "1px solid #f1f5f9",
    borderRadius: 10,
    background: "#fafafa",
  },
  infoLabel: {
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: ".02em",
    color: "#6b7280",
  },
  infoValue: {
    fontSize: 14,
    fontWeight: 600,
    color: "#111827",
    minHeight: 22,
    display: "inline-flex",
    alignItems: "center",
  },
  stageChip: {
    display: "inline-flex",
    alignItems: "center",
    borderRadius: 999,
    border: "1px solid",
    padding: ".2rem .56rem",
    fontSize: 12,
    fontWeight: 700,
    whiteSpace: "nowrap",
  },
  nextStageButton: {
    padding: ".52rem .86rem",
    borderRadius: 10,
    border: "1px solid #c7d2fe",
    background: "#eef2ff",
    color: "#3730a3",
    fontWeight: 600,
    cursor: "pointer",
    fontSize: 13,
    boxShadow: "0 1px 2px rgba(15, 23, 42, 0.08)",
    transition: "all 120ms ease",
  },
  nextStageButtonPressed: {
    transform: "translateY(1px)",
    background: "#e0e7ff",
    borderColor: "#a5b4fc",
    boxShadow: "0 0 0 rgba(0,0,0,0)",
  },
  nextStageButtonBusy: {
    opacity: 0.82,
    background: "#e5e7eb",
    color: "#374151",
    borderColor: "#d1d5db",
    cursor: "progress",
  },
  nextStageButtonDone: {
    borderColor: "#86efac",
    background: "#f0fdf4",
    color: "#166534",
    boxShadow: "0 1px 2px rgba(22, 101, 52, 0.12)",
  },
  signingButton: {
    padding: ".52rem .86rem",
    borderRadius: 10,
    border: "1px solid #86efac",
    background: "#f0fdf4",
    color: "#166534",
    fontWeight: 600,
    cursor: "pointer",
    fontSize: 13,
    boxShadow: "0 1px 2px rgba(22, 101, 52, 0.1)",
    transition: "all 120ms ease",
  },
  signingButtonPressed: {
    transform: "translateY(1px)",
    background: "#dcfce7",
    borderColor: "#4ade80",
    boxShadow: "0 0 0 rgba(0,0,0,0)",
  },
  signingButtonBusy: {
    opacity: 0.82,
    background: "#e5e7eb",
    color: "#374151",
    borderColor: "#d1d5db",
    cursor: "progress",
  },
  toolbar: {
    display: "flex",
    justifyContent: "space-between",
    gap: "1rem",
    padding: "1rem",
    borderBottom: "1px solid #e5e7eb",
    background: "#fafafa",
    alignItems: "center",
    flexWrap: "wrap",
  },
  riskHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "1rem 1rem .5rem",
    gap: ".8rem",
    flexWrap: "wrap",
  },
  riskTitle: {
    margin: 0,
    fontSize: 16,
    color: "#111827",
  },
  riskSubtitle: {
    fontSize: 12,
    color: "#6b7280",
    fontWeight: 600,
  },
  riskGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: ".7rem",
    padding: "0 1rem 1rem",
  },
  riskItem: {
    display: "flex",
    flexDirection: "column",
    gap: ".2rem",
    padding: ".65rem .7rem",
    border: "1px solid #f1f5f9",
    borderRadius: 10,
    background: "#fafafa",
  },
  riskSummaryBox: {
    margin: "0 1rem 1rem",
    padding: ".75rem .8rem",
    border: "1px solid #e5e7eb",
    borderRadius: 10,
    background: "#fff",
  },
  riskSummaryText: {
    margin: ".35rem 0 0",
    fontSize: 14,
    color: "#374151",
    lineHeight: 1.5,
  },
  riskChecklist: {
    margin: "0 1rem 1rem",
    padding: ".75rem .8rem",
    border: "1px solid #e5e7eb",
    borderRadius: 10,
    background: "#fff",
  },
  riskChecklistGrid: {
    marginTop: ".5rem",
    display: "grid",
    gap: ".55rem",
  },
  riskQuestionRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: ".7rem",
    flexWrap: "wrap",
  },
  riskQuestionText: {
    fontSize: 14,
    color: "#111827",
    fontWeight: 500,
  },
  riskToggleGroup: {
    display: "inline-flex",
    gap: ".42rem",
    alignItems: "center",
  },
  riskToggleButton: {
    padding: ".33rem .62rem",
    borderRadius: 8,
    border: "1px solid #d1d5db",
    background: "#fff",
    color: "#374151",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
  },
  riskToggleYesActive: {
    borderColor: "#86efac",
    background: "#f0fdf4",
    color: "#166534",
  },
  riskToggleNoActive: {
    borderColor: "#fecaca",
    background: "#fef2f2",
    color: "#991b1b",
  },
  riskLockHint: {
    margin: ".65rem 0 0",
    fontSize: 12,
    color: "#6b7280",
  },
  input: {
    padding: ".55rem .75rem",
    borderRadius: 12,
    border: "1px solid #e5e7eb",
    minWidth: 220,
    outline: "none",
  },
  topNavBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: ".8rem",
    padding: ".75rem .9rem",
    border: "1px solid #dbeafe",
    borderRadius: 12,
    background: "#eff6ff",
    marginBottom: "1rem",
    flexWrap: "wrap",
  },
  topBackLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: ".35rem",
    color: "#1d4ed8",
    textDecoration: "none",
    fontWeight: 700,
    background: "#fff",
    border: "1px solid #bfdbfe",
    borderRadius: 10,
    padding: ".45rem .7rem",
  },
  topCompanyBadge: {
    fontSize: 13,
    fontWeight: 700,
    color: "#1e3a8a",
    background: "#dbeafe",
    border: "1px solid #bfdbfe",
    borderRadius: 999,
    padding: ".35rem .7rem",
    whiteSpace: "nowrap",
  },
  nameInput: {
    padding: ".5rem .65rem",
    borderRadius: 10,
    border: "1px solid #d1d5db",
    outline: "none",
    minWidth: 160,
  },
  select: {
    padding: ".55rem .75rem",
    borderRadius: 12,
    border: "1px solid #e5e7eb",
    outline: "none",
    background: "#fff",
    minWidth: 150,
  },
  tableWrap: {
    overflowX: "auto",
  },
  table: {
    width: "100%",
    borderCollapse: "separate",
    borderSpacing: 0,
  },
  th: {
    textAlign: "left",
    fontSize: 12,
    letterSpacing: ".02em",
    textTransform: "uppercase",
    color: "#6b7280",
    padding: ".85rem 1rem",
    borderBottom: "1px solid #e5e7eb",
    background: "#fff",
    position: "sticky",
    top: 0,
    zIndex: 1,
    whiteSpace: "nowrap",
  },
  tr: {
    background: "#fff",
  },
  td: {
    padding: ".85rem 1rem",
    borderBottom: "1px solid #f3f4f6",
    verticalAlign: "top",
    color: "#111827",
    fontSize: 14,
  },
  tdStrong: {
    padding: ".85rem 1rem",
    borderBottom: "1px solid #f3f4f6",
    verticalAlign: "top",
    color: "#111827",
    fontSize: 14,
    fontWeight: 700,
    whiteSpace: "nowrap",
  },
  tdMono: {
    padding: ".85rem 1rem",
    borderBottom: "1px solid #f3f4f6",
    verticalAlign: "top",
    color: "#111827",
    fontSize: 13,
    fontFamily:
      "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
    whiteSpace: "nowrap",
    minWidth: 170,
  },
  note: {
    padding: "0.9rem 1rem",
    color: "#6b7280",
    fontSize: 13,
    background: "#fafafa",
    borderTop: "1px solid #e5e7eb",
  },
  statusSelectWrap: {
    position: "relative",
    display: "inline-flex",
    alignItems: "center",
    border: "1px solid #d1d5db",
    borderRadius: 999,
    paddingRight: "1.35rem",
    width: 150,
    flexShrink: 0,
  },
  statusSelect: {
    appearance: "none",
    WebkitAppearance: "none",
    MozAppearance: "none",
    border: "none",
    background: "transparent",
    padding: ".35rem .7rem",
    paddingRight: ".2rem",
    borderRadius: 999,
    outline: "none",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    width: "100%",
  },
  statusChevron: {
    position: "absolute",
    right: ".55rem",
    fontSize: 11,
    pointerEvents: "none",
    lineHeight: 1,
  },
  tdComment: {
    padding: ".85rem 1rem",
    borderBottom: "1px solid #f3f4f6",
    verticalAlign: "top",
    color: "#111827",
    fontSize: 14,
    minWidth: 360,
  },
  tdDiscussionWrap: {
    padding: ".35rem .8rem .75rem",
    borderBottom: "1px solid #f3f4f6",
    background: "#fff",
  },
  discussionToggleButton: {
    borderRadius: 8,
    border: "1px solid #d1d5db",
    background: "#fff",
    color: "#374151",
    padding: ".28rem .52rem",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  discussionPanel: {
    border: "1px solid #e5e7eb",
    borderRadius: 10,
    background: "#fafafa",
    padding: ".55rem .6rem",
  },
  discussionList: {
    display: "grid",
    gap: ".45rem",
    marginBottom: ".5rem",
    maxHeight: 220,
    overflowY: "auto",
  },
  discussionEmpty: {
    fontSize: 12,
    color: "#6b7280",
  },
  discussionItem: {
    background: "#fff",
    border: "1px solid #e5e7eb",
    borderRadius: 8,
    padding: ".42rem .5rem",
  },
  discussionMeta: {
    fontSize: 11,
    color: "#6b7280",
    marginBottom: ".2rem",
  },
  discussionMessage: {
    fontSize: 13,
    color: "#111827",
    whiteSpace: "pre-wrap",
    lineHeight: 1.4,
  },
  discussionComposer: {
    display: "flex",
    gap: ".45rem",
    alignItems: "flex-end",
  },
  discussionTextarea: {
    flex: 1,
    minHeight: 64,
    borderRadius: 8,
    border: "1px solid #d1d5db",
    padding: ".45rem .55rem",
    fontSize: 13,
    lineHeight: 1.4,
    outline: "none",
    resize: "vertical",
    fontFamily: "inherit",
    background: "#fff",
  },
  discussionSendButton: {
    borderRadius: 8,
    border: "1px solid #111827",
    background: "#111827",
    color: "#fff",
    fontSize: 12,
    fontWeight: 700,
    padding: ".35rem .55rem",
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  rowTextarea: {
    width: "100%",
    minWidth: 320,
    minHeight: 82,
    padding: ".55rem .65rem",
    borderRadius: 10,
    border: "1px solid #d1d5db",
    outline: "none",
    fontSize: 13,
    lineHeight: 1.4,
    resize: "none",
    overflow: "hidden",
    fontFamily: "inherit",
  },
  lockBar: {
    display: "flex",
    alignItems: "center",
    gap: ".6rem",
    padding: ".7rem 1rem",
    borderBottom: "1px solid #e5e7eb",
    background: "#f8fafc",
    flexWrap: "wrap",
  },
  lockButton: {
    padding: ".45rem .75rem",
    borderRadius: 10,
    border: "1px solid #111827",
    background: "#111827",
    color: "#fff",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  },
  forceReleaseButton: {
    borderColor: "#f59e0b",
    background: "#fffbeb",
    color: "#92400e",
  },
  lockText: {
    fontSize: 13,
    color: "#4b5563",
  },
  error: {
    padding: ".75rem 1rem",
    fontSize: 13,
    color: "#991b1b",
    background: "#fef2f2",
    borderBottom: "1px solid #fecaca",
  },
  savingSlot: {
    display: "inline-block",
    minWidth: 70,
  },
};
